<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   BL
 * @package    BL_CustomGrid
 * @copyright  Copyright (c) 2012 Benoît Leulliette <benoit.leulliette@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
    $_gridBlock   = $this->getGridBlock();
    $_gridModel   = $this->getGridModel();
?>
<script type="text/javascript">
//<![CDATA[
    <?php echo $this->getJsObjectName() ?> = new blcg.Grid.Editor('<?php echo $this->getGridTableId() ?>', <?php echo $this->getEditableColumnsJsonConfig() ?>, <?php echo $this->getRowsJsonConfig() ?>, <?php echo $this->getAdditionalParamsJson() ?>, <?php echo $this->getGlobalParamsJson() ?>, <?php echo $this->getErrorMessagesJson() ?>);
//]]>
</script>