<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   BL
 * @package    BL_CustomGrid
 * @copyright  Copyright (c) 2013 Benoît Leulliette <benoit.leulliette@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_columns = $this->getColumns() ?>
<?php if (!empty($_columns)): ?>
<table class="grid data blcg-additional-filters-table" cellspacing="0">
    <tr class="headings">
    <?php foreach ($_columns as $_column): ?>
        <th>
            <span class="nobr"><?php echo $_column->getHeader() ?></span>
        </th>
    <?php endforeach ?>
    </tr>
    <tr class="filter">
    <?php foreach ($_columns as $_column): ?>
        <th><?php echo $_column->getFilterHtml() ?></th>
    <?php endforeach ?>
    </tr>
</table>
<?php endif ?>