<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   BL
 * @package    BL_CustomGrid
 * @copyright  Copyright (c) 2014 Benoît Leulliette <benoit.leulliette@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_gridModel = $this->getGridModel() ?>
<div id="<?php echo $this->getHtmlId() ?>-additional" class="blcg-custom-grid-config-additional-container"<?php if (!$this->getStartDisplayed()): ?> style="display:none;"<?php endif ?>>
    <?php if ($this->canDisplayDefaultParamsBlocks()): ?>
        <div class="blcg-custom-grid-config-additional-part" id="<?php echo $this->getHtmlId() ?>-default-params-save">
            <div class="blcg-custom-grid-config-additional-part-label">
                <?php echo $this->__('Save As Custom Default Grid Parameters:') ?>
            </div>
            <div class="blcg-custom-grid-config-additional-part-content">
                <ul>
                    <li>
                        <input type="checkbox" value="<?php echo $this->getGridPageNumber() ?>" name="grid_default_params[page]" id="<?php echo $this->getHtmlId() ?>-grid-default-page-number" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-default-page-number"><?php echo $this->__('Page Number') ?></label>
                    </li>
                    <li>
                        <input type="checkbox" value="<?php echo $this->getGridPageSize() ?>" name="grid_default_params[limit]" id="<?php echo $this->getHtmlId() ?>-grid-default-page-size" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-default-page-size"><?php echo $this->__('Page Size') ?></label>
                    </li>
                    <li>
                        <input type="checkbox" value="<?php echo $this->getGridSort() ?>" name="grid_default_params[sort]" id="<?php echo $this->getHtmlId() ?>-grid-default-sort" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-default-sort"><?php echo $this->__('Sort') ?></label>
                    </li>
                    <li>
                        <input type="checkbox" value="<?php echo $this->getGridSortDirection() ?>" name="grid_default_params[dir]" id="<?php echo $this->getHtmlId() ?>-grid-default-dir" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-default-dir"><?php echo $this->__('Sort Direction') ?></label>
                    </li>
                    <li>
                        <input type="checkbox" value="<?php echo $this->getGridFilters() ?>" name="grid_default_params[filter]" id="<?php echo $this->getHtmlId() ?>-grid-default-filter" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-default-filter"><?php echo $this->__('Filters') ?></label>
                    </li>
                </ul>
                <div class="blcg-custom-grid-config-additional-part-actions">
                    <?php echo $this->getApplyButtonHtml($this->getDefaultParamsSaveJsObjectName() . '.save();') ?>
                </div>
            </div>
        </div>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getDefaultParamsSaveJsObjectName() ?> = new blcg.Grid.Form(
    '<?php echo $this->getHtmlId() ?>-default-params-save',
    '<?php echo $this->getDefaultParamsSaveUrl() ?>',
    <?php echo $this->getJsGridFormJsonConfig() ?>
);
//]]>
</script>
        <div class="blcg-custom-grid-config-additional-part" id="<?php echo $this->getHtmlId() ?>-default-params-remove">
            <div class="blcg-custom-grid-config-additional-part-label">
                <?php echo $this->__('Remove Custom Default Grid Parameters:') ?>
            </div>
            <div class="blcg-custom-grid-config-additional-part-content">
                <ul>
                    <li>
                        <input type="checkbox" value="1" name="remove_default_params[page]" id="<?php echo $this->getHtmlId() ?>-grid-remove-page-number" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-remove-page-number">
                            <?php echo $this->__('Page Number') ?> (<strong><?php if ($_gridModel->getDefaultPage()): ?><?php echo $_gridModel->getDefaultPage() ?><?php else: ?><?php echo $this->__('none') ?><?php endif ?></strong>)
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" value="1" name="remove_default_params[limit]" id="<?php echo $this->getHtmlId() ?>-grid-remove-page-size" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-remove-page-size">
                            <?php echo $this->__('Page Size') ?> (<strong><?php if ($_gridModel->getDefaultLimit()): ?><?php echo $_gridModel->getDefaultLimit() ?><?php else: ?><?php echo $this->__('none') ?><?php endif ?></strong>)
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" value="1" name="remove_default_params[sort]" id="<?php echo $this->getHtmlId() ?>-grid-remove-sort" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-remove-sort">
                            <?php echo $this->__('Sort') ?> (<strong><?php if ($_gridModel->getDefaultSort()): ?><?php echo $this->__('column "%s"', $this->htmlEscape($_gridModel->getColumnHeader($_gridModel->getDefaultSort()))) ?><?php else: ?><?php echo $this->__('none') ?><?php endif ?></strong>)
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" value="" name="remove_default_params[dir]" id="<?php echo $this->getHtmlId() ?>-grid-remove-dir" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-remove-dir">
                            <?php echo $this->__('Sort Direction') ?> (<strong><?php if ($_gridModel->getDefaultDir()): ?><?php echo $this->__($_gridModel->getDefaultDir() == 'asc' ? 'ascending' : 'descending') ?><?php else: ?><?php echo $this->__('none') ?><?php endif ?></strong>)
                        </label>
                    </li>
                    <li>
                        <input type="checkbox" value="1" name="remove_default_params[filter]" id="<?php echo $this->getHtmlId() ?>-grid-remove-filter" />
                        <label for="<?php echo $this->getHtmlId() ?>-grid-remove-filter">
                            <?php echo $this->__('Filters') ?> (<strong><?php if ($_gridModel->getDefaultFilter()): ?><?php echo $this->__('existing') ?><?php else: ?><?php echo $this->__('none') ?><?php endif ?></strong>)
                        </label>
                    </li>
                </ul>
                <div class="blcg-custom-grid-config-additional-part-actions">
                    <?php echo $this->getApplyButtonHtml($this->getDefaultParamsRemoveJsObjectName() . '.save();') ?>
                </div>
            </div>
        </div>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getDefaultParamsRemoveJsObjectName() ?> = new blcg.Grid.Form(
    '<?php echo $this->getHtmlId() ?>-default-params-remove',
    '<?php echo $this->getDefaultParamsSaveUrl() ?>',
    <?php echo $this->getJsGridFormJsonConfig() ?>
);
//]]>
</script>
    <?php endif ?>
    <?php if ($this->canDisplayCustomColumnsBlock()): ?>
        <div class="blcg-custom-grid-config-additional-part" id="<?php echo $this->getHtmlId() ?>-custom-columns-save">
            <div class="blcg-custom-grid-config-additional-part-label">
                <?php echo $this->__('Custom Columns:') ?>
            </div>
            <div class="blcg-custom-grid-config-additional-part-content">
                <?php
                    $_customColumns = $this->getCustomColumns();
                    $_columnsGroups = $this->getCustomColumnsGroups();
                    $_displayGroups = (count($_columnsGroups) > 1);
                    $_previousGroup = null;
                ?>
                <div id="<?php echo $this->getHtmlId() ?>-custom-columns-wrapper" class="blcg-custom-columns-wrapper">
                <?php foreach ($_columnsGroups as $_groupId => $_group): ?>
                    <?php if ($_displayGroups): ?>
                        <?php if ($_previousGroup): ?></div><?php endif; $_previousGroup = $_groupId ?>
                        <div class="blcg-custom-columns-group">
                            <?php $_startDisplayed = false ?>
                            <?php
                                $_totalCount = 0;
                                $_displayedCount = 0;
                                
                                foreach ($_customColumns[$_groupId] as $_column):
                                    $_totalCount++;
                                    
                                    if ($_column->getSelected()):
                                        $_displayedCount++;
                                    endif;
                                endforeach;
                            ?>
                            <div class="blcg-custom-columns-group-label <?php if ($_startDisplayed): ?>blcg-custom-columns-group-label-on<?php else: ?>blcg-custom-columns-group-label-off<?php endif ?>">
                                <?php echo $this->htmlEscape($_group) ?>
                                <span><?php echo $this->__('(%s/%s)', $_displayedCount, $_totalCount) ?></span>
                            </div>
                            <div class="blcg-custom-columns-list" <?php if (!$_startDisplayed): ?>style="display:none;"<?php endif ?>>
                    <?php else: ?>
                        <div class="blcg-custom-columns-list">
                    <?php endif ?>
                    <?php foreach ($_customColumns[$_groupId] as $_column): ?>
                        <div class="blcg-custom-columns-column">
                            <label title="<?php echo $this->htmlEscape($_column->getName()) ?>">
                                <input type="checkbox" name="custom_columns[]" value="<?php echo $_column->getId() ?>"<?php if ($_column->getSelected()): ?> checked="checked"<?php endif ?> />
                                <span><?php echo $this->htmlEscape($_column->getName()) ?></span>
                            </label>
                            <div class="blcg-custom-columns-column-buttons">
                                <?php if (($_warning = trim($_column->getWarning())) !== ''): ?>
                                    <div class="blcg-custom-columns-column-button blcg-custom-columns-column-button-warning">
                                        <div class="blcg-custom-columns-tooltip">
                                            <div class="blcg-custom-columns-help-text blcg-custom-columns-help-single-text"><?php echo $_warning ?></div>
                                        </div>
                                    </div>
                                <?php endif ?>
                                <div class="blcg-custom-columns-column-button blcg-custom-columns-column-button-help">
                                    <div class="blcg-custom-columns-tooltip">
                                        <?php if (($_description = trim($_column->getDescription())) !== ''): ?>
                                            <div class="blcg-custom-columns-help-text"><?php echo $_description ?></div>
                                        <?php endif ?>
                                        <ul class="blcg-custom-columns-help-features">
                                            <li class="blcg-custom-columns-help-feature-<?php if ($_column->getAllowStore()): ?>with<?php else: ?>without<?php endif ?>">
                                                <?php echo $this->__('Selectable Store View') ?>
                                            </li>
                                            <li class="blcg-custom-columns-help-feature-<?php if ($_column->getAllowRenderers()): ?>with<?php else: ?>without<?php endif ?>">
                                                <?php echo $this->__('Selectable Renderer') ?>
                                            </li>
                                            <li class="blcg-custom-columns-help-feature-<?php if ($_column->getAllowCustomization()): ?>with<?php else: ?>without<?php endif ?>">
                                                <?php echo $this->__('Customization Parameters') ?>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
                    </div>
                <?php endforeach ?>
                <?php if ($_displayGroups): ?></div><?php endif ?>
                </div>
                <div class="blcg-custom-grid-config-additional-part-actions">
                    <?php echo $this->getApplyButtonHtml($this->getCustomColumnsSaveJsObjectName() . '.save();') ?>
                </div>
            </div>
        </div>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getCustomColumnsListJsObjectName() ?> = new blcg.Grid.CustomColumn.List('<?php echo $this->getHtmlId() ?>-custom-columns-wrapper');
<?php echo $this->getCustomColumnsSaveJsObjectName() ?> = new blcg.Grid.Form(
    '<?php echo $this->getHtmlId() ?>-custom-columns-save',
    '<?php echo $this->getCustomColumnsSaveUrl() ?>',
    <?php echo $this->getJsGridFormJsonConfig() ?>
);
//]]>
</script>
    <?php endif ?>
    <?php if ($this->canDisplayExportBlock()): ?>
        <div class="blcg-custom-grid-config-additional-part" id="<?php echo $this->getHtmlId() ?>-export">
            <div class="blcg-custom-grid-config-additional-part-label">
                <img src="<?php echo $this->getSkinUrl('bl/customgrid/images/export.png') ?>" alt="" class="v-middle"/>
                <?php echo $this->__('Export:') ?>
            </div>
            <div class="blcg-custom-grid-config-additional-part-content">
                <ul>
                    <li>
                        <?php echo $this->__('Format:') ?>
                        <select name="export[format]" id="<?php echo $this->getHtmlId() ?>-export-format">
                            <option value=""></option>
                            <?php foreach ($this->getExportTypes() as $_type): ?>
                                <option value="<?php echo $_type->getUrl() ?>"><?php echo $this->htmlEscape($_type->getLabel()) ?></option>
                            <?php endforeach ?>
                        </select>
                    </li>
                    <li>
                        <?php echo $this->__('Size:') ?>
                        <select name="export[size]" id="<?php echo $this->getHtmlId() ?>-export-size">
                            <option value="<?php echo $this->getGridSize() ?>"><?php echo $this->__('Total (%s)', $this->getGridSize()) ?></option>
                            <?php // @todo use custom sizes ?>
                            <option value="20">20</option>
                            <option value="30">30</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                            <option value="200">200</option>
                            <option value=""><?php echo $this->__('Other') ?></option>
                        </select>&nbsp;<input type="text" class="blcg-pagination-input" name="export[custom_size]" id="<?php echo $this->getHtmlId() ?>-export-custom-size" style="display: none;" disabled="disabled" />
                    </li>
                    <li>
                        <?php echo $this->__('From Result:') ?>
                        <input type="text" class="blcg-pagination-input" name="export[from_result]" value="<?php echo (($this->getGridPageNumber()-1) * $this->getGridPageSize() +1) ?>" id="<?php echo $this->getHtmlId() ?>-export-from-result">
                    </li>
                </ul>
                <div class="blcg-custom-grid-config-additional-part-actions">
                    <?php echo $this->getApplyButtonHtml($this->getExportJsObjectName() . '.doExport();', $this->__('Export')) ?>
                </div>
            </div>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getExportJsObjectName() ?> = new blcg.Grid.ExportForm(
    '<?php echo $this->getHtmlId() ?>-export',
    <?php echo $this->getJsGridFormJsonConfig() ?>
);
//]]>
</script>
        </div>
    <?php endif ?>
    <div class="blcg-clearer"></div>
</div>