<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   BL
 * @package    BL_CustomGrid
 * @copyright  Copyright (c) 2014 Benoît Leulliette <benoit.leulliette@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="blcg-collection-renderers-descriptions" style="display: none;">
    <div class="blcg-content-header">
        <h3 class="icon-head head-adminhtml"><?php echo $this->__('Columns Types Descriptions') ?></h3>
    </div>
    <dl class="blcg-collection-renderers-descriptions-list">
    <?php foreach ($this->_getAvailableRenderers() as $_renderer): ?>
        <dt><?php echo $this->htmlEscape($_renderer->getName()) ?></dt>
        <dd>
        <?php if (trim($_description = $_renderer->getDescription()) !== ''): ?>
            <?php echo $this->htmlEscape($_description) ?>
        <?php else: ?>
            <?php echo $this->__('No Description') ?>
        <?php endif ?>
        </dd>
    <?php endforeach ?>
    </dl>
</div>
<script type="text/javascript">
function blcgDisplayCollectionRenderersHelp()
{
    blcg.Tools.openDialogFromElement(
        'blcg-collection-renderers-descriptions',
        {title: '<?php echo $this->jsQuoteEscape($this->__('Help')) ?>'}
    );
}
</script>