<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   BL
 * @package    BL_CustomGrid
 * @copyright  Copyright (c) 2012 Benoît Leulliette <benoit.leulliette@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (!$this->getEditedInGrid()): ?>
<div class="entry-edit">
<?php endif ?>
    <?php echo $this->getFormHtml();?>
<?php if (!$this->getEditedInGrid()): ?>
</div>
<?php endif ?>
<?php echo $this->getChildHtml('form_after');?>