<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   BL
 * @package    BL_CustomGrid
 * @copyright  Copyright (c) 2014 Benoît Leulliette <benoit.leulliette@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <h3 class="icon-head head-products"><?php echo $this->getHeader() ?></h3>
    <p class="content-buttons form-buttons">
        <?php echo $this->getBackButtonHtml() ?>
        <?php echo $this->getCancelButtonHtml() ?>
        <?php if($this->getOptionsSourceId()): ?>
            <?php echo $this->getDeleteButtonHtml() ?>
        <?php endif ?>
        <?php if($this->getOptionsSourceType()): ?>
            <?php echo $this->getSaveButtonHtml() ?>
            <?php echo $this->getSaveAndEditButtonHtml() ?>
        <?php endif ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="blcg_options_source_edit_form" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
    <div style="display: none;"></div>
</form>
<script type="text/javascript">
//<![CDATA[
var blcgOptionsSourceTemplateSyntax = /(^|.|\r|\n)({{(\w+)}})/;
var blcgOptionsSourceForm = new varienForm('blcg_options_source_edit_form');

function saveAndContinueEdit(urlTemplate)
{
    var template = new Template(urlTemplate, blcgOptionsSourceTemplateSyntax);
    var url = template.evaluate({tab_id: blcg_options_source_tabsJsTabs.activeTab.id});
    blcgOptionsSourceForm.submit(url);
}

function setSettings(urlTemplate, typeElement)
{
    var template = new Template(urlTemplate, blcgOptionsSourceTemplateSyntax);
    setLocation(template.evaluate({type: $F(typeElement)}));
}

Event.observe(window, 'load', function() {
    if ('<?php echo $this->getSelectedTabId() ?>') {
        var selectedTab = $('<?php echo $this->getSelectedTabId() ?>');
        blcg_options_source_tabsJsTabs.setSkipDisplayFirstTab();
        blcg_options_source_tabsJsTabs.showTabContent(selectedTab);
    }
});
//]]>
</script>